# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: LongAT.LongATTest
PackageVersion: 1.0.0
InstallerType: inno
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
UpgradeBehavior: install
Commands:
  - LongATTest
AppsAndFeaturesEntries:
  - DisplayName: Long AT Test version 1.0.0
    Publisher: Long AT
    DisplayVersion: 1.0.0
    ProductCode: '{9F573DF1-0F46-4B83-9B3B-8C6BE76A96C2}_is1'
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/vulongvy/LongATTest/releases/download/v1.0.0/LongATTest-Setup-1.0.0.exe
    InstallerSha256: 0984996C87C01D969396709BA9C9567C99C25D69FBBAB0201E5C8790F68A7750
ManifestType: installer
ManifestVersion: 1.6.0
